import { readFileSync, readdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import type { Plugin } from 'vite';

const MESSAGES_DIR = join(process.cwd(), 'messages');
const OUTPUT_PATH = join(process.cwd(), 'src/lib/messages.ts');

function getLocales(): readonly string[] {
	const files = readdirSync(MESSAGES_DIR)
		.filter((f) => f.endsWith('.json') && f !== 'package.json')
		.map((f) => f.replace('.json', ''));

	const preferredOrder = ['en', 'de', 'fr', 'zh', 'cn', 'ru'];
	const ordered = preferredOrder.filter((l) => files.includes(l));
	const remaining = files.filter((l) => !ordered.includes(l)).sort();

	return [...ordered, ...remaining];
}

function loadMessages(): Record<string, string[]> {
	const locales = getLocales();
	const localeIndex: Record<string, number> = {};
	locales.forEach((locale, index) => {
		localeIndex[locale] = index;
	});

	const all: Record<string, string[]> = {};
	for (const locale of locales) {
		const filePath = join(MESSAGES_DIR, `${locale}.json`);
		const content = JSON.parse(readFileSync(filePath, 'utf-8'));

		for (const [key, value] of Object.entries(content)) {
			if (key === '$schema') continue;
			if (!all[key]) all[key] = new Array(locales.length);
			all[key][localeIndex[locale]] = value as string;
		}
	}

	return all;
}

function generateCode(msgs: Record<string, string[]>): string {
	const locales = getLocales();
	const localeIndex: Record<string, number> = {};
	locales.forEach((locale, index) => {
		localeIndex[locale] = index;
	});

	const messageExports = Object.entries(msgs)
		.map(([key, tr]) => `export function ${key}(p?: Record<string, string | number>): string { return _t(${JSON.stringify(tr)}, p); }`)
		.join('\n');

	return `// Auto-generated by i18n-plugin. Do not edit.
export const locales = ${JSON.stringify(Array.from(locales))} as const;
export const cookieName = 'LOCALE';
export const cookieMaxAge = 34560000;

import { writable } from 'svelte/store';

let _storage: import('node:async_hooks').AsyncLocalStorage<{ locale: string }> | null | undefined = undefined;

const _localeStore = writable('${locales[0]}');

export const locale = _localeStore;

export function getLocale(): string {
  if (_storage) { const s = _storage.getStore(); if (s?.locale) return s.locale; }
  let currentLocale = '${locales[0]}';
  _localeStore.subscribe(l => currentLocale = l)();
  if (typeof document !== 'undefined') { const l = document.documentElement.lang; if (l) return l; }
  return currentLocale;
}

export function getLocales() { return locales; }

export function setLocale(locale: string): void {
  if (!(locales as readonly string[]).includes(locale)) return;
  _localeStore.set(locale);
  if (typeof document !== 'undefined') {
    document.documentElement.lang = locale;
    document.cookie = cookieName + '=' + locale + '; path=/; max-age=' + cookieMaxAge;
  }
}

export function getTextDirection(locale: string): string {
  return ['ar', 'he', 'fa', 'ur'].includes(locale) ? 'rtl' : 'ltr';
}

export function deLocalizeUrl(url: URL | string): URL {
  return typeof url === 'string' ? new URL(url) : url;
}

export async function runWithLocale<T>(locale: string, fn: () => T | Promise<T>): Promise<T> {
  if (_storage === undefined) {
    try {
      const { AsyncLocalStorage } = await import(/* @vite-ignore */ 'node:async_hooks');
      _storage = new AsyncLocalStorage();
    } catch {
      _storage = null;
    }
  }
  if (_storage) return _storage.run({ locale }, fn) as Promise<T>;
  return fn() as Promise<T>;
}

const _li: Record<string, number> = ${JSON.stringify(localeIndex)};

function _t(tr: string[], p?: Record<string, string | number>): string {
  const text = tr[_li[getLocale()] ?? 0] ?? tr[0] ?? '';
  if (!p) return text;
  return text.replace(/\\{(\\w+)\\}/g, (_, k) => String(p[k] ?? '{' + k + '}'));
}

${messageExports}`;
}

function generate(): void {
	const msgs = loadMessages();
	writeFileSync(OUTPUT_PATH, generateCode(msgs));
}

export function i18nPlugin(): Plugin {
	return {
		name: 'i18n-plugin',

		buildStart() {
			generate();
		},

		configureServer(server) {
			generate();
			server.watcher.add(MESSAGES_DIR);
			server.watcher.on('change', (file) => {
				if (file.startsWith(MESSAGES_DIR) && file.endsWith('.json')) {
					generate();
				}
			});
		}
	};
}
