// Auto-generated by i18n-plugin. Do not edit.
export const locales = ["cn","de","en","ru"] as const;
export const cookieName = 'LOCALE';
export const cookieMaxAge = 34560000;

let _storage: import('node:async_hooks').AsyncLocalStorage<{ locale: string }> | null | undefined = undefined;

export function getLocale(): string {
  if (_storage) { const s = _storage.getStore(); if (s?.locale) return s.locale; }
  if (typeof document !== 'undefined') { const l = document.documentElement.lang; if (l) return l; }
  return 'cn';
}

export function getLocales() { return locales; }

export function setLocale(locale: string): void {
  if (typeof document !== 'undefined' && (locales as readonly string[]).includes(locale)) document.documentElement.lang = locale;
}

export function getTextDirection(locale: string): string {
  return ['ar', 'he', 'fa', 'ur'].includes(locale) ? 'rtl' : 'ltr';
}

export function deLocalizeUrl(url: URL | string): URL {
  return typeof url === 'string' ? new URL(url) : url;
}

export async function runWithLocale<T>(locale: string, fn: () => T | Promise<T>): Promise<T> {
  if (_storage === undefined) {
    try {
      const { AsyncLocalStorage } = await import(/* @vite-ignore */ 'node:async_hooks');
      _storage = new AsyncLocalStorage();
    } catch {
      _storage = null;
    }
  }
  if (_storage) return _storage.run({ locale }, fn) as Promise<T>;
  return fn() as Promise<T>;
}

const _li: Record<string, number> = {"cn":0,"de":1,"en":2,"ru":3};

function _t(tr: string[], p?: Record<string, string | number>): string {
  const text = tr[_li[getLocale()] ?? 0] ?? tr[0] ?? '';
  if (!p) return text;
  return text.replace(/\{(\w+)\}/g, (_, k) => String(p[k] ?? '{' + k + '}'));
}

export function title(p?: Record<string, string | number>): string { return _t(["RizinOS - 第一个在线操作系统","RizinOS - Das erste Online-Betriebssystem","RizinOS - The First Online Operating System","RizinOS - Первое онлайн-операционная система"], p); }
export function description(p?: Record<string, string | number>): string { return _t(["现代的基于网络的操作系统，彻底改变您的工作方式。随时随地可用，始终保持同步。","Das moderne webbasierte Betriebssystem, das Ihre Arbeit revolutioniert. Überall verfügbar, immer synchronisiert.","The modern web-based operating system that revolutionizes your work. Available everywhere, always synchronized.","Современная веб-операционная система, которая революционизирует вашу работу. Доступна везде, всегда синхронизирована."], p); }
export function copyright(p?: Record<string, string | number>): string { return _t(["版权所有。","Alle Rechte vorbehalten.","All rights reserved.","Все права защищены."], p); }
export function features(p?: Record<string, string | number>): string { return _t(["功能","Funktionen","Features","Функции"], p); }
export function overview(p?: Record<string, string | number>): string { return _t(["概览","Überblick","Overview","Обзор"], p); }
export function performance(p?: Record<string, string | number>): string { return _t(["性能","Leistung","Performance","Производительность"], p); }
export function security(p?: Record<string, string | number>): string { return _t(["安全性","Sicherheit","Security","Безопасность"], p); }
export function integration(p?: Record<string, string | number>): string { return _t(["集成","Integration","Integration","Интеграция"], p); }
export function documentation(p?: Record<string, string | number>): string { return _t(["文档","Dokumentation","Documentation","Документация"], p); }
export function getting_started(p?: Record<string, string | number>): string { return _t(["快速开始","Erste Schritte","Getting Started","Начало работы"], p); }
export function api_reference(p?: Record<string, string | number>): string { return _t(["API 参考","API-Referenz","API Reference","API справочник"], p); }
export function tutorials(p?: Record<string, string | number>): string { return _t(["教程","Tutorials","Tutorials","Руководства"], p); }
export function pricing(p?: Record<string, string | number>): string { return _t(["价格","Preise","Pricing","Цены"], p); }
export function enterprise(p?: Record<string, string | number>): string { return _t(["企业版","Enterprise","Enterprise","Корпоративным клиентам"], p); }
export function privacy_policy(p?: Record<string, string | number>): string { return _t(["隐私政策","Datenschutz","Privacy Policy","Политика конфиденциальности"], p); }
export function terms_of_service(p?: Record<string, string | number>): string { return _t(["服务条款","AGB","Terms of Service","Условия использования"], p); }
export function cookies(p?: Record<string, string | number>): string { return _t(["Cookies","Cookies","Cookies","Cookies"], p); }
export function imprint(p?: Record<string, string | number>): string { return _t(["法律信息","Impressum","Imprint","Юридическая информация"], p); }
export function product(p?: Record<string, string | number>): string { return _t(["产品","Produkt","Product","Продукт"], p); }
export function resources(p?: Record<string, string | number>): string { return _t(["资源","Ressourcen","Resources","Ресурсы"], p); }
export function status(p?: Record<string, string | number>): string { return _t(["状态","Status","Status","Статус"], p); }
export function blog(p?: Record<string, string | number>): string { return _t(["博客","Blog","Blog","Блог"], p); }
export function company(p?: Record<string, string | number>): string { return _t(["公司","Unternehmen","Company","Компания"], p); }
export function about_us(p?: Record<string, string | number>): string { return _t(["关于我们","Über uns","About Us","О нас"], p); }
export function careers(p?: Record<string, string | number>): string { return _t(["招聘","Karriere","Careers","Карьера"], p); }
export function contact(p?: Record<string, string | number>): string { return _t(["联系方式","Kontakt","Contact","Контакты"], p); }
export function legal(p?: Record<string, string | number>): string { return _t(["法律信息","Rechtliches","Legal","Правовая информация"], p); }
export function hello_world(p?: Record<string, string | number>): string { return _t([null,null,"Hello, {name} from en!",null], p); }