// Auto-generated by i18n-plugin. Do not edit.
export const locales = ["en","de","cn","ru"] as const;
export const cookieName = 'LOCALE';
export const cookieMaxAge = 34560000;

import { writable } from 'svelte/store';

let _storage: import('node:async_hooks').AsyncLocalStorage<{ locale: string }> | null | undefined = undefined;

let _currentLocale = 'en';
const _localeStore = writable('en');

_localeStore.subscribe(l => _currentLocale = l);

export const locale = _localeStore;

export function getLocale(): string {
  if (_storage) { const s = _storage.getStore(); if (s?.locale) return s.locale; }
  if (typeof document !== 'undefined') { const l = document.documentElement.lang; if (l) return l; }
  return _currentLocale;
}

export function getLocales() { return locales; }

export function setLocale(locale: string): void {
  if (!(locales as readonly string[]).includes(locale)) return;
  _localeStore.set(locale);
  if (typeof document !== 'undefined') {
    document.documentElement.lang = locale;
    document.cookie = cookieName + '=' + locale + '; path=/; max-age=' + cookieMaxAge;
  }
}

export function getTextDirection(locale: string): string {
  return ['ar', 'he', 'fa', 'ur'].includes(locale) ? 'rtl' : 'ltr';
}

export function deLocalizeUrl(url: URL | string): URL {
  return typeof url === 'string' ? new URL(url) : url;
}

export async function runWithLocale<T>(locale: string, fn: () => T | Promise<T>): Promise<T> {
  if (_storage === undefined) {
    try {
      const { AsyncLocalStorage } = await import(/* @vite-ignore */ 'node:async_hooks');
      _storage = new AsyncLocalStorage();
    } catch {
      _storage = null;
    }
  }
  if (_storage) return _storage.run({ locale }, fn) as Promise<T>;
  return fn() as Promise<T>;
}

const _li: Record<string, number> = {"en":0,"de":1,"cn":2,"ru":3};

function _t(tr: string[], p?: Record<string, string | number>): string {
  const text = tr[_li[getLocale()] ?? 0] ?? tr[0] ?? '';
  if (!p) return text;
  return text.replace(/\{(\w+)\}/g, (_, k) => String(p[k] ?? '{' + k + '}'));
}

export function title(p?: Record<string, string | number>): string { return _t(["RizinOS - The First Online Operating System","RizinOS - Das erste Online-Betriebssystem","RizinOS - 第一个在线操作系统","RizinOS - Первая онлайн-операционная система"], p); }
export function description(p?: Record<string, string | number>): string { return _t(["The modern web-based operating system that revolutionizes your work. Available everywhere, always synchronized.","Das moderne webbasierte Betriebssystem, das Ihre Arbeit revolutioniert. Überall verfügbar, immer synchronisiert.","现代的基于网络的操作系统，彻底改变您的工作方式。随时随地可用，始终保持同步。","Современная веб-операционная система, которая революционизирует вашу работу. Доступна везде, всегда синхронизирована."], p); }
export function copyright(p?: Record<string, string | number>): string { return _t(["All rights reserved.","Alle Rechte vorbehalten.","版权所有。","Все права защищены."], p); }
export function features(p?: Record<string, string | number>): string { return _t(["Features","Funktionen","功能","Функции"], p); }
export function overview(p?: Record<string, string | number>): string { return _t(["Overview","Überblick","概览","Обзор"], p); }
export function performance(p?: Record<string, string | number>): string { return _t(["Performance","Leistung","性能","Производительность"], p); }
export function security(p?: Record<string, string | number>): string { return _t(["Security","Sicherheit","安全性","Безопасность"], p); }
export function integration(p?: Record<string, string | number>): string { return _t(["Integration","Integration","集成","Интеграция"], p); }
export function documentation(p?: Record<string, string | number>): string { return _t(["Documentation","Dokumentation","文档","Документация"], p); }
export function getting_started(p?: Record<string, string | number>): string { return _t(["Getting Started","Erste Schritte","快速开始","Начало работы"], p); }
export function api_reference(p?: Record<string, string | number>): string { return _t(["API Reference","API-Referenz","API 参考","API справочник"], p); }
export function tutorials(p?: Record<string, string | number>): string { return _t(["Tutorials","Tutorials","教程","Руководства"], p); }
export function pricing(p?: Record<string, string | number>): string { return _t(["Pricing","Preise","价格","Цены"], p); }
export function enterprise(p?: Record<string, string | number>): string { return _t(["Enterprise","Enterprise","企业版","Корпоративным клиентам"], p); }
export function privacy_policy(p?: Record<string, string | number>): string { return _t(["Privacy Policy","Datenschutz","隐私政策","Политика конфиденциальности"], p); }
export function terms_of_service(p?: Record<string, string | number>): string { return _t(["Terms of Service","AGB","服务条款","Условия использования"], p); }
export function cookies(p?: Record<string, string | number>): string { return _t(["Cookies","Cookies","Cookies","Cookies"], p); }
export function imprint(p?: Record<string, string | number>): string { return _t(["Imprint","Impressum","法律信息","Юридическая информация"], p); }
export function product(p?: Record<string, string | number>): string { return _t(["Product","Produkt","产品","Продукт"], p); }
export function resources(p?: Record<string, string | number>): string { return _t(["Resources","Ressourcen","资源","Ресурсы"], p); }
export function status(p?: Record<string, string | number>): string { return _t(["Status","Status","状态","Статус"], p); }
export function blog(p?: Record<string, string | number>): string { return _t(["Blog","Blog","博客","Блог"], p); }
export function company(p?: Record<string, string | number>): string { return _t(["Company","Unternehmen","公司","Компания"], p); }
export function about_us(p?: Record<string, string | number>): string { return _t(["About Us","Über uns","关于我们","О нас"], p); }
export function careers(p?: Record<string, string | number>): string { return _t(["Careers","Karriere","招聘","Карьера"], p); }
export function contact(p?: Record<string, string | number>): string { return _t(["Contact","Kontakt","联系方式","Контакты"], p); }
export function legal(p?: Record<string, string | number>): string { return _t(["Legal","Rechtliches","法律信息","Правовая информация"], p); }
export function open_your_os(p?: Record<string, string | number>): string { return _t(["Open your OS","Ihr OS öffnen","打开您的操作系统","Открыть вашу ОС"], p); }
export function log_in(p?: Record<string, string | number>): string { return _t(["Log in","Anmelden","登录","Войти"], p); }
export function language(p?: Record<string, string | number>): string { return _t(["Language","Sprache","语言","Язык"], p); }
export function hero_title(p?: Record<string, string | number>): string { return _t(["The operating system that runs in your browser","Das Betriebssystem, das in Ihrem Browser läuft","在您的浏览器中运行的操作系统","Операционная система, которая работает в вашем браузере"], p); }
export function hero_subtitle(p?: Record<string, string | number>): string { return _t(["Built on Rust WASM modules and a NixOS-inspired architecture. No hardware. No drivers. No OS errors. By design. Adapts to your device: feels at home on phones, tablets, and desktops alike.","Aufgebaut auf Rust WASM-Modulen und einer NixOS-inspirierten Architektur. Keine Hardware. Keine Treiber. Keine OS-Fehler. By design. Passt sich Ihrem Gerät an: auf Smartphones, Tablets und Desktops gleichermaßen zuhause.","基于 Rust WASM 模块和受 NixOS 启发的架构构建。无需硬件。无需驱动程序。没有系统错误。源于设计。适应您的设备：在手机、平板电脑和桌面上都如鱼得水。","Построена на модулях Rust WASM и архитектуре, вдохновлённой NixOS. Никакого железа. Никаких драйверов. Никаких ошибок ОС. По задумке. Адаптируется к вашему устройству: одинаково удобна на смартфонах, планшетах и десктопах."], p); }
export function core_promise_label(p?: Record<string, string | number>): string { return _t(["The core promise","Das Kernversprechen","核心承诺","Главное обещание"], p); }
export function zero_errors_title(p?: Record<string, string | number>): string { return _t(["The first OS that cannot fail.","Das erste OS, das nicht versagen kann.","第一个不会崩溃的操作系统。","Первая ОС, которая не может сломаться."], p); }
export function zero_errors_desc(p?: Record<string, string | number>): string { return _t(["Traditional operating systems fail because they depend on hardware, drivers, and mutable state. RizinOS eliminates all three. Running in the browser means no hardware abstractions to break, no drivers to conflict, and no system state to corrupt.","Traditionelle Betriebssysteme versagen, weil sie von Hardware, Treibern und veränderbarem Zustand abhängen. RizinOS eliminiert alle drei. Der Betrieb im Browser bedeutet keine Hardwareabstraktionen, die brechen können, keine Treiberkonflikte und keinen Systemzustand, der korrumpiert werden kann.","传统操作系统会崩溃，因为它们依赖于硬件、驱动程序和可变状态。RizinOS 消除了这三者。在浏览器中运行意味着没有可能损坏的硬件抽象层，没有驱动冲突，也没有可能损坏的系统状态。","Традиционные операционные системы дают сбои, потому что зависят от железа, драйверов и изменяемого состояния. RizinOS устраняет все три. Работа в браузере означает отсутствие аппаратных абстракций, которые могут сломаться, конфликтов драйверов и системного состояния, которое может быть нарушено."], p); }
export function hardware_independent_title(p?: Record<string, string | number>): string { return _t(["Hardware-independent","Hardwareunabhängig","硬件独立","Независимость от железа"], p); }
export function hardware_independent_desc(p?: Record<string, string | number>): string { return _t(["No device drivers. No hardware conflicts. The browser is the hardware layer, and browsers are extremely good at that job.","Keine Gerätetreiber. Keine Hardwarekonflikte. Der Browser ist die Hardwareschicht, und Browser sind darin ausgezeichnet.","无需设备驱动程序。无硬件冲突。浏览器就是硬件层，而浏览器非常擅长这项工作。","Никаких драйверов устройств. Никаких аппаратных конфликтов. Браузер — это аппаратный слой, и браузеры справляются с этой задачей отлично."], p); }
export function declarative_config_title(p?: Record<string, string | number>): string { return _t(["Declarative configuration","Deklarative Konfiguration","声明式配置","Декларативная конфигурация"], p); }
export function declarative_config_desc(p?: Record<string, string | number>): string { return _t(["Every system setting is version-controlled and reproducible. No configuration drift between environments, ever.","Jede Systemeinstellung ist versioniert und reproduzierbar. Keine Konfigurationsabweichungen zwischen Umgebungen, niemals.","每个系统设置都经过版本控制且可重现。环境之间永远不会出现配置漂移。","Каждая настройка системы версионирована и воспроизводима. Никаких расхождений конфигурации между средами — никогда."], p); }
export function atomic_updates_title(p?: Record<string, string | number>): string { return _t(["Atomic updates","Atomare Updates","原子更新","Атомарные обновления"], p); }
export function atomic_updates_desc(p?: Record<string, string | number>): string { return _t(["System updates apply atomically or not at all. Failed updates roll back automatically. You can undo any change, any time.","Systemupdates werden atomar angewendet oder gar nicht. Fehlgeschlagene Updates werden automatisch zurückgerollt. Sie können jede Änderung jederzeit rückgängig machen.","系统更新要么完整应用，要么根本不应用。失败的更新会自动回滚。您可以随时撤销任何更改。","Обновления системы применяются атомарно или не применяются вовсе. Неудачные обновления откатываются автоматически. Вы можете отменить любое изменение в любое время."], p); }
export function capabilities_label(p?: Record<string, string | number>): string { return _t(["Capabilities","Funktionen","功能特性","Возможности"], p); }
export function features_era_title(p?: Record<string, string | number>): string { return _t(["Built for the next era of computing.","Gebaut für die nächste Ära des Computings.","为计算的下一个时代而生。","Создана для новой эры вычислений."], p); }
export function feature_rust_wasm_title(p?: Record<string, string | number>): string { return _t(["Rust WASM Engine","Rust WASM Engine","Rust WASM 引擎","Движок Rust WASM"], p); }
export function feature_rust_wasm_desc(p?: Record<string, string | number>): string { return _t(["Core OS modules written in Rust, compiled to WebAssembly. Near-native performance, entirely in the browser.","Kern-OS-Module in Rust geschrieben, zu WebAssembly kompiliert. Nahezu native Leistung, vollständig im Browser.","核心操作系统模块用 Rust 编写，编译为 WebAssembly。近乎原生的性能，完全在浏览器中运行。","Основные модули ОС написаны на Rust и скомпилированы в WebAssembly. Производительность, близкая к нативной, полностью в браузере."], p); }
export function feature_nixos_title(p?: Record<string, string | number>): string { return _t(["NixOS-like Architecture","NixOS-ähnliche Architektur","类 NixOS 架构","Архитектура в стиле NixOS"], p); }
export function feature_nixos_desc(p?: Record<string, string | number>): string { return _t(["Declarative, version-controlled system configuration. Roll back any change at any time.","Deklarative, versionierte Systemkonfiguration. Jede Änderung jederzeit zurückrollen.","声明式、版本控制的系统配置。随时回滚任何更改。","Декларативная, версионированная конфигурация системы. Откат любого изменения в любое время."], p); }
export function feature_encryption_title(p?: Record<string, string | number>): string { return _t(["Client-Side Encryption","Clientseitige Verschlüsselung","客户端加密","Шифрование на стороне клиента"], p); }
export function feature_encryption_desc(p?: Record<string, string | number>): string { return _t(["All storage is encrypted before it leaves your device. The server never sees your plaintext.","Alle Daten werden verschlüsselt, bevor sie Ihr Gerät verlassen. Der Server sieht niemals Ihren Klartext.","所有存储在离开您的设备之前都经过加密。服务器永远看不到您的明文。","Все данные шифруются до того, как покидают ваше устройство. Сервер никогда не видит открытый текст."], p); }
export function feature_instant_title(p?: Record<string, string | number>): string { return _t(["Instant Start","Sofortstart","即时启动","Мгновенный старт"], p); }
export function feature_instant_desc(p?: Record<string, string | number>): string { return _t(["No POST. No drivers. No loading. Open a tab and your OS is there, exactly as you left it.","Kein POST. Keine Treiber. Keine Ladezeiten. Öffnen Sie einen Tab - Ihr OS ist da, genau wie Sie es verlassen haben.","无 POST。无驱动程序。无加载。打开标签页，您的操作系统就在那里，与您离开时完全相同。","Никаких POST-запросов. Никаких драйверов. Никакой загрузки. Откройте вкладку - и ваша ОС уже там, точно так, как вы её оставили."], p); }
export function feature_bgapp_title(p?: Record<string, string | number>): string { return _t(["Background App","Hintergrund-App","后台应用","Фоновое приложение"], p); }
export function feature_bgapp_desc(p?: Record<string, string | number>): string { return _t(["Optional native companion for file sync, peripheral access, and push notifications from your device.","Optionaler nativer Begleiter für Dateisynchronisation, Peripheriezugriff und Push-Benachrichtigungen von Ihrem Gerät.","可选的本地伴侣应用，用于文件同步、外设访问和来自设备的推送通知。","Опциональный нативный компаньон для синхронизации файлов, доступа к периферии и push-уведомлений с вашего устройства."], p); }
export function feature_collab_title(p?: Record<string, string | number>): string { return _t(["Real-Time Collaboration","Echtzeit-Zusammenarbeit","实时协作","Совместная работа в реальном времени"], p); }
export function feature_collab_desc(p?: Record<string, string | number>): string { return _t(["Shared sessions on files and apps, built at the OS level. Not bolted on per-app.","Gemeinsame Sitzungen auf Dateien und Apps, auf OS-Ebene eingebaut. Nicht nachträglich pro App hinzugefügt.","在操作系统层面构建的文件和应用程序共享会话，而非每个应用程序单独附加的功能。","Совместные сессии на файлах и приложениях, встроенные на уровне ОС. Не надстройка поверх каждого приложения."], p); }
export function bg_app_label(p?: Record<string, string | number>): string { return _t(["Background App","Hintergrund-App","后台应用","Фоновое приложение"], p); }
export function bg_app_title(p?: Record<string, string | number>): string { return _t(["Extends into your device.","Erweitert sich auf Ihr Gerät.","延伸到您的设备。","Расширяется на ваше устройство."], p); }
export function bg_app_desc(p?: Record<string, string | number>): string { return _t(["Install the optional Background App to bridge RizinOS with your device. File sync, peripheral access, and native notifications, without giving up the browser-first architecture.","Installieren Sie die optionale Hintergrund-App, um RizinOS mit Ihrem Gerät zu verbinden. Dateisynchronisation, Peripheriezugriff und native Benachrichtigungen, ohne die Browser-First-Architektur aufzugeben.","安装可选的后台应用，将 RizinOS 与您的设备连接起来。文件同步、外设访问和本地通知，同时保持浏览器优先架构。","Установите опциональное фоновое приложение для связи RizinOS с вашим устройством. Синхронизация файлов, доступ к периферии и нативные уведомления - без отказа от браузерной архитектуры."], p); }
export function sync_bidirectional(p?: Record<string, string | number>): string { return _t(["Bidirectional file sync between device and cloud VFS","Bidirektionale Dateisynchronisation zwischen Gerät und Cloud-VFS","设备与云端 VFS 之间的双向文件同步","Двунаправленная синхронизация файлов между устройством и облачным VFS"], p); }
export function sync_native_dnd(p?: Record<string, string | number>): string { return _t(["Native drag-and-drop uploads from your desktop","Native Drag-and-Drop-Uploads von Ihrem Desktop","从桌面原生拖放上传","Нативная загрузка перетаскиванием с рабочего стола"], p); }
export function sync_backups(p?: Record<string, string | number>): string { return _t(["Continuous versioned backups with configurable retention","Kontinuierliche versionierte Backups mit konfigurierbarer Aufbewahrungsdauer","具有可配置保留期的持续版本化备份","Непрерывные версионированные резервные копии с настраиваемым сроком хранения"], p); }
export function sync_push_notif(p?: Record<string, string | number>): string { return _t(["Push notifications even when the browser tab is closed","Push-Benachrichtigungen auch wenn der Browser-Tab geschlossen ist","即使关闭浏览器标签页也能收到推送通知","Push-уведомления даже при закрытой вкладке браузера"], p); }
export function sync_peripherals(p?: Record<string, string | number>): string { return _t(["Peripheral bridging: cameras, microphones, USB, serial","Peripherie-Brücke: Kameras, Mikrofone, USB, Seriell","外设桥接：摄像头、麦克风、USB、串行","Связь с периферией: камеры, микрофоны, USB, последовательный порт"], p); }
export function sync_offline(p?: Record<string, string | number>): string { return _t(["Offline mode with automatic sync on reconnect","Offline-Modus mit automatischer Synchronisation bei Wiederverbindung","离线模式，重新连接时自动同步","Офлайн-режим с автоматической синхронизацией при восстановлении соединения"], p); }
export function download_for(p?: Record<string, string | number>): string { return _t(["Download for {platform}","Herunterladen für {platform}","下载 {platform} 版本","Скачать для {platform}"], p); }
export function arch_label(p?: Record<string, string | number>): string { return _t(["Architecture","Architektur","架构","Архитектура"], p); }
export function arch_title(p?: Record<string, string | number>): string { return _t(["Clean layers, no shortcuts.","Saubere Schichten, keine Abkürzungen.","清晰的层次，没有捷径。","Чистые слои, никаких компромиссов."], p); }
export function arch_desc(p?: Record<string, string | number>): string { return _t(["Rust modules compile to WASM and run as the kernel layer. SvelteKit drives the system shell. Each app is an isolated WASM process with its own memory space and typed IPC to the OS. Nothing is shared implicitly.","Rust-Module werden zu WASM kompiliert und als Kernel-Schicht ausgeführt. SvelteKit steuert die System-Shell. Jede App ist ein isolierter WASM-Prozess mit eigenem Speicherbereich und typisiertem IPC zum OS. Nichts wird implizit geteilt.","Rust 模块编译为 WASM 并作为内核层运行。SvelteKit 驱动系统外壳。每个应用程序都是一个独立的 WASM 进程，具有自己的内存空间和到操作系统的类型化 IPC。没有任何内容是隐式共享的。","Модули Rust компилируются в WASM и выполняются как уровень ядра. SvelteKit управляет системной оболочкой. Каждое приложение — изолированный WASM-процесс с собственным пространством памяти и типизированным IPC к ОС. Ничего не передаётся неявно."], p); }
export function arch_ipc_note(p?: Record<string, string | number>): string { return _t(["All layers communicate through typed IPC interfaces","Alle Schichten kommunizieren über typisierte IPC-Schnittstellen","所有层通过类型化 IPC 接口进行通信","Все слои общаются через типизированные интерфейсы IPC"], p); }
export function applications_label(p?: Record<string, string | number>): string { return _t(["Applications","Anwendungen","应用程序","Приложения"], p); }
export function apps_title(p?: Record<string, string | number>): string { return _t(["A full suite. Built in.","Eine vollständige Suite. Eingebaut.","完整套件，内置集成。","Полный набор. Встроенный."], p); }
export function apps_desc(p?: Record<string, string | number>): string { return _t(["Every app shares a unified permission model, file protocol, and design system. They are OS citizens, not plugins.","Jede App teilt ein einheitliches Berechtigungsmodell, Dateiprotokoll und Design-System. Sie sind OS-Bürger, keine Plugins.","每个应用程序共享统一的权限模型、文件协议和设计系统。它们是操作系统的一等公民，而非插件。","Каждое приложение использует единую модель разрешений, файловый протокол и дизайн-систему. Они — граждане ОС, а не плагины."], p); }
export function apps_roadmap(p?: Record<string, string | number>): string { return _t(["+ Minecraft integration, AI assistant, Stripe payments, video calling in the roadmap","+ Minecraft-Integration, KI-Assistent, Stripe-Zahlungen, Videoanrufe in der Roadmap","+ Minecraft 集成、AI 助手、Stripe 支付、视频通话已在路线图中","+ Интеграция с Minecraft, ИИ-ассистент, платежи Stripe, видеозвонки в roadmap"], p); }
export function cta_title(p?: Record<string, string | number>): string { return _t(["Your OS is waiting. Open a tab.","Ihr OS wartet. Öffnen Sie einen Tab.","您的操作系统在等待。打开一个标签页。","Ваша ОС ждёт. Откройте вкладку."], p); }
export function cta_desc(p?: Record<string, string | number>): string { return _t(["No downloads. No setup. Works on any device, any screen size, any browser.","Keine Downloads. Kein Setup. Funktioniert auf jedem Gerät, jeder Bildschirmgröße, jedem Browser.","无需下载。无需设置。适用于任何设备、任何屏幕尺寸、任何浏览器。","Без загрузок. Без настройки. Работает на любом устройстве, любом размере экрана, в любом браузере."], p); }
export function cta_button(p?: Record<string, string | number>): string { return _t(["Create your account","Konto erstellen","创建您的账户","Создать аккаунт"], p); }
export function cta_note(p?: Record<string, string | number>): string { return _t(["Free tier forever - No credit card - 10 GB cloud storage included","Dauerhaft kostenlos - Keine Kreditkarte - 10 GB Cloud-Speicher inklusive","永久免费 - 无需信用卡 - 包含 10 GB 云存储","Бесплатно навсегда - Без кредитной карты - 10 ГБ облачного хранилища включено"], p); }
export function login_welcome_label(p?: Record<string, string | number>): string { return _t(["Welcome back","Willkommen zurück","欢迎回来","С возвращением"], p); }
export function login_tagline(p?: Record<string, string | number>): string { return _t(["Your OS is waiting for you.","Ihr OS wartet auf Sie.","您的操作系统在等待您。","Ваша ОС ждёт вас."], p); }
export function login_tagline_desc(p?: Record<string, string | number>): string { return _t(["Sign in to access your cloud desktop from any device, anywhere.","Melden Sie sich an, um von jedem Gerät, überall auf Ihren Cloud-Desktop zuzugreifen.","登录以从任何设备、任何地方访问您的云桌面。","Войдите, чтобы получить доступ к облачному рабочему столу с любого устройства, где угодно."], p); }
export function login_highlight_encrypted(p?: Record<string, string | number>): string { return _t(["End-to-end encrypted storage","Ende-zu-Ende-verschlüsselter Speicher","端到端加密存储","Хранилище со сквозным шифрованием"], p); }
export function login_highlight_any_device(p?: Record<string, string | number>): string { return _t(["Access from any device, any browser","Zugriff von jedem Gerät, in jedem Browser","从任何设备、任何浏览器访问","Доступ с любого устройства, в любом браузере"], p); }
export function login_highlight_instant(p?: Record<string, string | number>): string { return _t(["Instant - no setup, no downloads","Sofort - kein Setup, keine Downloads","即时 - 无需设置，无需下载","Мгновенно - никакой настройки, никаких загрузок"], p); }
export function login_sign_in_title(p?: Record<string, string | number>): string { return _t(["Sign in","Anmelden","登录","Войти"], p); }
export function login_sign_in_desc(p?: Record<string, string | number>): string { return _t(["Enter your credentials to continue.","Geben Sie Ihre Anmeldedaten ein, um fortzufahren.","输入您的凭据以继续。","Введите ваши учётные данные для продолжения."], p); }
export function login_email_label(p?: Record<string, string | number>): string { return _t(["Email","E-Mail","电子邮件","Электронная почта"], p); }
export function login_password_label(p?: Record<string, string | number>): string { return _t(["Password","Passwort","密码","Пароль"], p); }
export function login_forgot_password(p?: Record<string, string | number>): string { return _t(["Forgot password?","Passwort vergessen?","忘记密码？","Забыли пароль?"], p); }
export function login_sign_in_button(p?: Record<string, string | number>): string { return _t(["Sign in","Anmelden","登录","Войти"], p); }
export function login_no_account(p?: Record<string, string | number>): string { return _t(["Don't have an account?","Noch kein Konto?","没有账户？","Нет аккаунта?"], p); }
export function login_create_one(p?: Record<string, string | number>): string { return _t(["Create one","Eines erstellen","创建一个","Создать"], p); }
export function signup_open_rizinos(p?: Record<string, string | number>): string { return _t(["Open RizinOS in your browser","RizinOS in Ihrem Browser öffnen","在您的浏览器中打开 RizinOS","Открыть RizinOS в браузере"], p); }
export function signup_open_your_os(p?: Record<string, string | number>): string { return _t(["Open your OS","Ihr OS öffnen","打开您的操作系统","Открыть вашу ОС"], p); }
export function signup_free_note(p?: Record<string, string | number>): string { return _t(["Free forever - No credit card required - GDPR compliant","Für immer kostenlos - Keine Kreditkarte erforderlich - DSGVO-konform","永久免费 - 无需信用卡 - 符合 GDPR","Бесплатно навсегда - Без кредитной карты - Соответствует GDPR"], p); }
export function signup_username_placeholder(p?: Record<string, string | number>): string { return _t(["choose a username","Benutzernamen wählen","选择用户名","выберите имя пользователя"], p); }
export function signup_tos_text(p?: Record<string, string | number>): string { return _t(["I have read and agree to RizinOS' Terms of Service and Privacy Policy.","Ich habe die Nutzungsbedingungen und die Datenschutzrichtlinie von RizinOS gelesen und stimme zu.","我已阅读并同意 RizinOS 的服务条款和隐私政策。","Я прочитал и соглашаюсь с Условиями использования и Политикой конфиденциальности RizinOS."], p); }
export function signup_welcome(p?: Record<string, string | number>): string { return _t(["Welcome, {username}!","Willkommen, {username}!","欢迎，{username}！","Добро пожаловать, {username}!"], p); }
export function signup_birthdate_prompt(p?: Record<string, string | number>): string { return _t(["When were you born?","Wann wurden Sie geboren?","您的出生日期是？","Когда вы родились?"], p); }
export function signup_continue(p?: Record<string, string | number>): string { return _t(["Continue","Weiter","继续","Продолжить"], p); }
export function signup_birthdate_required(p?: Record<string, string | number>): string { return _t(["Please enter your date of birth.","Bitte geben Sie Ihr Geburtsdatum ein.","请输入您的出生日期。","Пожалуйста, укажите дату рождения."], p); }
export function signup_age_requirement(p?: Record<string, string | number>): string { return _t(["You must be at least 13 years old.","Sie müssen mindestens 13 Jahre alt sein.","您必须年满 13 岁。","Вам должно быть не менее 13 лет."], p); }
export function signup_finish_title(p?: Record<string, string | number>): string { return _t(["Finish signing up","Registrierung abschließen","完成注册","Завершить регистрацию"], p); }
export function signup_finish_desc(p?: Record<string, string | number>): string { return _t(["Claim your account by entering an email and password.","Sichern Sie Ihr Konto mit einer E-Mail-Adresse und einem Passwort.","输入电子邮件和密码来创建您的账户。","Защитите аккаунт, указав электронную почту и пароль."], p); }
export function signup_email_placeholder(p?: Record<string, string | number>): string { return _t(["Email","E-Mail","电子邮件","Электронная почта"], p); }
export function signup_password_placeholder(p?: Record<string, string | number>): string { return _t(["Password","Passwort","密码","Пароль"], p); }
export function signup_creating(p?: Record<string, string | number>): string { return _t(["Creating account...","Konto wird erstellt...","正在创建账户...","Создание аккаунта..."], p); }
export function signup_create_account(p?: Record<string, string | number>): string { return _t(["Create account","Konto erstellen","创建账户","Создать аккаунт"], p); }
export function signup_thanks_title(p?: Record<string, string | number>): string { return _t(["Thanks!","Danke!","谢谢！","Спасибо!"], p); }
export function signup_confirm_sent(p?: Record<string, string | number>): string { return _t(["We've sent a confirmation link to:","Wir haben einen Bestätigungslink gesendet an:","我们已向以下地址发送确认链接：","Мы отправили ссылку для подтверждения на:"], p); }
export function signup_check_spam(p?: Record<string, string | number>): string { return _t(["Check your spam folder if you don't see it.","Überprüfen Sie Ihren Spam-Ordner, falls Sie ihn nicht sehen.","如果您没有看到它，请检查垃圾邮件文件夹。","Проверьте папку спама, если не видите письма."], p); }
export function signup_email_invalid(p?: Record<string, string | number>): string { return _t(["Enter a valid email address.","Geben Sie eine gültige E-Mail-Adresse ein.","请输入有效的电子邮件地址。","Введите корректный адрес электронной почты."], p); }
export function signup_password_too_short(p?: Record<string, string | number>): string { return _t(["Must be at least 8 characters.","Muss mindestens 8 Zeichen lang sein.","必须至少 8 个字符。","Должен содержать не менее 8 символов."], p); }
export function signup_show_password(p?: Record<string, string | number>): string { return _t(["Show password","Passwort anzeigen","显示密码","Показать пароль"], p); }
export function signup_hide_password(p?: Record<string, string | number>): string { return _t(["Hide password","Passwort verbergen","隐藏密码","Скрыть пароль"], p); }
export function signup_username_required(p?: Record<string, string | number>): string { return _t(["Please choose a username.","Bitte wähle einen Benutzernamen.","请选择一个用户名。","Пожалуйста, выберите имя пользователя."], p); }
export function signup_username_too_short(p?: Record<string, string | number>): string { return _t(["Username must be at least 3 characters.","Der Benutzername muss mindestens 3 Zeichen lang sein.","用户名至少需要 3 个字符。","Имя пользователя должно содержать не менее 3 символов."], p); }
export function signup_username_too_long(p?: Record<string, string | number>): string { return _t(["Username must be at most 20 characters.","Der Benutzername darf höchstens 20 Zeichen lang sein.","用户名最多 20 个字符。","Имя пользователя не должно превышать 20 символов."], p); }
export function signup_username_invalid_chars(p?: Record<string, string | number>): string { return _t(["Only letters, numbers, underscores, and hyphens are allowed.","Nur Buchstaben, Zahlen, Unterstriche und Bindestriche sind erlaubt.","只允许使用字母、数字、下划线和连字符。","Допускаются только буквы, цифры, знаки подчёркивания и дефисы."], p); }
export function signup_birthdate_invalid(p?: Record<string, string | number>): string { return _t(["Please enter a valid date.","Bitte gib ein gültiges Datum ein.","请输入有效的日期。","Пожалуйста, введите корректную дату."], p); }
export function signup_birthdate_future(p?: Record<string, string | number>): string { return _t(["Date of birth cannot be in the future.","Das Geburtsdatum darf nicht in der Zukunft liegen.","出生日期不能是未来的日期。","Дата рождения не может быть в будущем."], p); }