// Auto-generated by i18n-plugin. Do not edit.
export const locales = ["de","en","cn","ru"] as const;
export const cookieName = 'LOCALE';
export const cookieMaxAge = 34560000;

import { writable } from 'svelte/store';

let _storage: import('node:async_hooks').AsyncLocalStorage<{ locale: string }> | null | undefined = undefined;

let _currentLocale = 'de';
const _localeStore = writable('de');

_localeStore.subscribe(l => _currentLocale = l);

export const locale = _localeStore;

export function getLocale(): string {
  if (_storage) { const s = _storage.getStore(); if (s?.locale) return s.locale; }
  if (typeof document !== 'undefined') { const l = document.documentElement.lang; if (l) return l; }
  return _currentLocale;
}

export function getLocales() { return locales; }

export function setLocale(locale: string): void {
  if (!(locales as readonly string[]).includes(locale)) return;
  _localeStore.set(locale);
  if (typeof document !== 'undefined') {
    document.documentElement.lang = locale;
    document.cookie = cookieName + '=' + locale + '; path=/; max-age=' + cookieMaxAge;
  }
}

export function getTextDirection(locale: string): string {
  return ['ar', 'he', 'fa', 'ur'].includes(locale) ? 'rtl' : 'ltr';
}

export function deLocalizeUrl(url: URL | string): URL {
  return typeof url === 'string' ? new URL(url) : url;
}

export async function runWithLocale<T>(locale: string, fn: () => T | Promise<T>): Promise<T> {
  if (_storage === undefined) {
    try {
      const { AsyncLocalStorage } = await import(/* @vite-ignore */ 'node:async_hooks');
      _storage = new AsyncLocalStorage();
    } catch {
      _storage = null;
    }
  }
  if (_storage) return _storage.run({ locale }, fn) as Promise<T>;
  return fn() as Promise<T>;
}

const _li: Record<string, number> = {"de":0,"en":1,"cn":2,"ru":3};

function _t(tr: string[], p?: Record<string, string | number>): string {
  const text = tr[_li[getLocale()] ?? 0] ?? tr[0] ?? '';
  if (!p) return text;
  return text.replace(/\{(\w+)\}/g, (_, k) => String(p[k] ?? '{' + k + '}'));
}

export function signup_open_rizinos(p?: Record<string, string | number>): string { return _t(["RizinOS in Ihrem Browser öffnen","Open RizinOS in your browser","在您的浏览器中打开 RizinOS","Открыть RizinOS в браузере"], p); }
export function signup_open_your_os(p?: Record<string, string | number>): string { return _t(["Ihr OS öffnen","Open your OS","打开您的操作系统","Открыть вашу ОС"], p); }
export function signup_free_note(p?: Record<string, string | number>): string { return _t(["Für immer kostenlos - Keine Kreditkarte erforderlich - DSGVO-konform","Free forever - No credit card required - GDPR compliant","永久免费 - 无需信用卡 - 符合 GDPR","Бесплатно навсегда - Без кредитной карты - Соответствует GDPR"], p); }
export function signup_username_placeholder(p?: Record<string, string | number>): string { return _t(["Benutzernamen wählen","choose a username","选择用户名","выберите имя пользователя"], p); }
export function signup_tos_text(p?: Record<string, string | number>): string { return _t(["Ich habe die Nutzungsbedingungen und die Datenschutzrichtlinie von RizinOS gelesen und stimme zu.","I have read and agree to RizinOS' Terms of Service and Privacy Policy.","我已阅读并同意 RizinOS 的服务条款和隐私政策。","Я прочитал и соглашаюсь с Условиями использования и Политикой конфиденциальности RizinOS."], p); }
export function signup_welcome(p?: Record<string, string | number>): string { return _t(["Willkommen, {username}!","Welcome, {username}!","欢迎，{username}！","Добро пожаловать, {username}!"], p); }
export function signup_birthdate_prompt(p?: Record<string, string | number>): string { return _t(["Wann wurden Sie geboren?","When were you born?","您的出生日期是？","Когда вы родились?"], p); }
export function signup_continue(p?: Record<string, string | number>): string { return _t(["Weiter","Continue","继续","Продолжить"], p); }
export function signup_birthdate_required(p?: Record<string, string | number>): string { return _t(["Bitte geben Sie Ihr Geburtsdatum ein.","Please enter your date of birth.","请输入您的出生日期。","Пожалуйста, укажите дату рождения."], p); }
export function signup_age_requirement(p?: Record<string, string | number>): string { return _t(["Sie müssen mindestens 13 Jahre alt sein.","You must be at least 13 years old.","您必须年满 13 岁。","Вам должно быть не менее 13 лет."], p); }
export function signup_finish_title(p?: Record<string, string | number>): string { return _t(["Registrierung abschließen","Finish signing up","完成注册","Завершить регистрацию"], p); }
export function signup_finish_desc(p?: Record<string, string | number>): string { return _t(["Sichern Sie Ihr Konto mit einer E-Mail-Adresse und einem Passwort.","Claim your account by entering an email and password.","输入电子邮件和密码来创建您的账户。","Защитите аккаунт, указав электронную почту и пароль."], p); }
export function signup_email_placeholder(p?: Record<string, string | number>): string { return _t(["E-Mail","Email","电子邮件","Электронная почта"], p); }
export function signup_password_placeholder(p?: Record<string, string | number>): string { return _t(["Passwort","Password","密码","Пароль"], p); }
export function signup_creating(p?: Record<string, string | number>): string { return _t(["Konto wird erstellt...","Creating account...","正在创建账户...","Создание аккаунта..."], p); }
export function signup_create_account(p?: Record<string, string | number>): string { return _t(["Konto erstellen","Create account","创建账户","Создать аккаунт"], p); }
export function signup_thanks_title(p?: Record<string, string | number>): string { return _t(["Danke!","Thanks!","谢谢！","Спасибо!"], p); }
export function signup_confirm_sent(p?: Record<string, string | number>): string { return _t(["Wir haben einen Bestätigungslink gesendet an:","We've sent a confirmation link to:","我们已向以下地址发送确认链接：","Мы отправили ссылку для подтверждения на:"], p); }
export function signup_check_spam(p?: Record<string, string | number>): string { return _t(["Überprüfen Sie Ihren Spam-Ordner, falls Sie ihn nicht sehen.","Check your spam folder if you don't see it.","如果您没有看到它，请检查垃圾邮件文件夹。","Проверьте папку спама, если не видите письма."], p); }
export function signup_email_invalid(p?: Record<string, string | number>): string { return _t(["Geben Sie eine gültige E-Mail-Adresse ein.","Enter a valid email address.","请输入有效的电子邮件地址。","Введите корректный адрес электронной почты."], p); }
export function signup_password_too_short(p?: Record<string, string | number>): string { return _t(["Muss mindestens 8 Zeichen lang sein.","Must be at least 8 characters.","必须至少 8 个字符。","Должен содержать не менее 8 символов."], p); }
export function signup_show_password(p?: Record<string, string | number>): string { return _t(["Passwort anzeigen","Show password","显示密码","Показать пароль"], p); }
export function signup_hide_password(p?: Record<string, string | number>): string { return _t(["Passwort verbergen","Hide password","隐藏密码","Скрыть пароль"], p); }
export function signup_username_required(p?: Record<string, string | number>): string { return _t(["Bitte wähle einen Benutzernamen.","Please choose a username.","请选择一个用户名。","Пожалуйста, выберите имя пользователя."], p); }
export function signup_username_too_short(p?: Record<string, string | number>): string { return _t(["Der Benutzername muss mindestens 3 Zeichen lang sein.","Username must be at least 3 characters.","用户名至少需要 3 个字符。","Имя пользователя должно содержать не менее 3 символов."], p); }
export function signup_username_too_long(p?: Record<string, string | number>): string { return _t(["Der Benutzername darf höchstens 20 Zeichen lang sein.","Username must be at most 20 characters.","用户名最多 20 个字符。","Имя пользователя не должно превышать 20 символов."], p); }
export function signup_username_invalid_chars(p?: Record<string, string | number>): string { return _t(["Nur Buchstaben, Zahlen, Unterstriche und Bindestriche sind erlaubt.","Only letters, numbers, underscores, and hyphens are allowed.","只允许使用字母、数字、下划线和连字符。","Допускаются только буквы, цифры, знаки подчёркивания и дефисы."], p); }
export function signup_birthdate_invalid(p?: Record<string, string | number>): string { return _t(["Bitte gib ein gültiges Datum ein.","Please enter a valid date.","请输入有效的日期。","Пожалуйста, введите корректную дату."], p); }
export function signup_birthdate_future(p?: Record<string, string | number>): string { return _t(["Das Geburtsdatum darf nicht in der Zukunft liegen.","Date of birth cannot be in the future.","出生日期不能是未来的日期。","Дата рождения не может быть в будущем."], p); }
export function hero_title(p?: Record<string, string | number>): string { return _t(["Das Betriebssystem, das in Ihrem Browser läuft","The operating system that runs in your browser","在您的浏览器中运行的操作系统","Операционная система, которая работает в вашем браузере"], p); }
export function hero_subtitle(p?: Record<string, string | number>): string { return _t(["Aufgebaut auf Rust WASM-Modulen und einer NixOS-inspirierten Architektur. Keine Hardware. Keine Treiber. Keine OS-Fehler. By design. Passt sich Ihrem Gerät an: auf Smartphones, Tablets und Desktops gleichermaßen zuhause.","Built on Rust WASM modules and a NixOS-inspired architecture. No hardware. No drivers. No OS errors. By design. Adapts to your device: feels at home on phones, tablets, and desktops alike.","基于 Rust WASM 模块和受 NixOS 启发的架构构建。无需硬件。无需驱动程序。没有系统错误。源于设计。适应您的设备：在手机、平板电脑和桌面上都如鱼得水。","Построена на модулях Rust WASM и архитектуре, вдохновлённой NixOS. Никакого железа. Никаких драйверов. Никаких ошибок ОС. По задумке. Адаптируется к вашему устройству: одинаково удобна на смартфонах, планшетах и десктопах."], p); }
export function core_promise_label(p?: Record<string, string | number>): string { return _t(["Das Kernversprechen","The core promise","核心承诺","Главное обещание"], p); }
export function zero_errors_title(p?: Record<string, string | number>): string { return _t(["Das erste OS, das nicht versagen kann.","The first OS that cannot fail.","第一个不会崩溃的操作系统。","Первая ОС, которая не может сломаться."], p); }
export function zero_errors_desc(p?: Record<string, string | number>): string { return _t(["Traditionelle Betriebssysteme versagen, weil sie von Hardware, Treibern und veränderbarem Zustand abhängen. RizinOS eliminiert alle drei. Der Betrieb im Browser bedeutet keine Hardwareabstraktionen, die brechen können, keine Treiberkonflikte und keinen Systemzustand, der korrumpiert werden kann.","Traditional operating systems fail because they depend on hardware, drivers, and mutable state. RizinOS eliminates all three. Running in the browser means no hardware abstractions to break, no drivers to conflict, and no system state to corrupt.","传统操作系统会崩溃，因为它们依赖于硬件、驱动程序和可变状态。RizinOS 消除了这三者。在浏览器中运行意味着没有可能损坏的硬件抽象层，没有驱动冲突，也没有可能损坏的系统状态。","Традиционные операционные системы дают сбои, потому что зависят от железа, драйверов и изменяемого состояния. RizinOS устраняет все три. Работа в браузере означает отсутствие аппаратных абстракций, которые могут сломаться, конфликтов драйверов и системного состояния, которое может быть нарушено."], p); }
export function hardware_independent_title(p?: Record<string, string | number>): string { return _t(["Hardwareunabhängig","Hardware-independent","硬件独立","Независимость от железа"], p); }
export function hardware_independent_desc(p?: Record<string, string | number>): string { return _t(["Keine Gerätetreiber. Keine Hardwarekonflikte. Der Browser ist die Hardwareschicht, und Browser sind darin ausgezeichnet.","No device drivers. No hardware conflicts. The browser is the hardware layer, and browsers are extremely good at that job.","无需设备驱动程序。无硬件冲突。浏览器就是硬件层，而浏览器非常擅长这项工作。","Никаких драйверов устройств. Никаких аппаратных конфликтов. Браузер — это аппаратный слой, и браузеры справляются с этой задачей отлично."], p); }
export function declarative_config_title(p?: Record<string, string | number>): string { return _t(["Deklarative Konfiguration","Declarative configuration","声明式配置","Декларативная конфигурация"], p); }
export function declarative_config_desc(p?: Record<string, string | number>): string { return _t(["Jede Systemeinstellung ist versioniert und reproduzierbar. Keine Konfigurationsabweichungen zwischen Umgebungen, niemals.","Every system setting is version-controlled and reproducible. No configuration drift between environments, ever.","每个系统设置都经过版本控制且可重现。环境之间永远不会出现配置漂移。","Каждая настройка системы версионирована и воспроизводима. Никаких расхождений конфигурации между средами — никогда."], p); }
export function atomic_updates_title(p?: Record<string, string | number>): string { return _t(["Atomare Updates","Atomic updates","原子更新","Атомарные обновления"], p); }
export function atomic_updates_desc(p?: Record<string, string | number>): string { return _t(["Systemupdates werden atomar angewendet oder gar nicht. Fehlgeschlagene Updates werden automatisch zurückgerollt. Sie können jede Änderung jederzeit rückgängig machen.","System updates apply atomically or not at all. Failed updates roll back automatically. You can undo any change, any time.","系统更新要么完整应用，要么根本不应用。失败的更新会自动回滚。您可以随时撤销任何更改。","Обновления системы применяются атомарно или не применяются вовсе. Неудачные обновления откатываются автоматически. Вы можете отменить любое изменение в любое время."], p); }
export function capabilities_label(p?: Record<string, string | number>): string { return _t(["Funktionen","Capabilities","功能特性","Возможности"], p); }
export function features_era_title(p?: Record<string, string | number>): string { return _t(["Gebaut für die nächste Ära des Computings.","Built for the next era of computing.","为计算的下一个时代而生。","Создана для новой эры вычислений."], p); }
export function feature_rust_wasm_title(p?: Record<string, string | number>): string { return _t(["Rust WASM Engine","Rust WASM Engine","Rust WASM 引擎","Движок Rust WASM"], p); }
export function feature_rust_wasm_desc(p?: Record<string, string | number>): string { return _t(["Kern-OS-Module in Rust geschrieben, zu WebAssembly kompiliert. Nahezu native Leistung, vollständig im Browser.","Core OS modules written in Rust, compiled to WebAssembly. Near-native performance, entirely in the browser.","核心操作系统模块用 Rust 编写，编译为 WebAssembly。近乎原生的性能，完全在浏览器中运行。","Основные модули ОС написаны на Rust и скомпилированы в WebAssembly. Производительность, близкая к нативной, полностью в браузере."], p); }
export function feature_nixos_title(p?: Record<string, string | number>): string { return _t(["NixOS-ähnliche Architektur","NixOS-like Architecture","类 NixOS 架构","Архитектура в стиле NixOS"], p); }
export function feature_nixos_desc(p?: Record<string, string | number>): string { return _t(["Deklarative, versionierte Systemkonfiguration. Jede Änderung jederzeit zurückrollen.","Declarative, version-controlled system configuration. Roll back any change at any time.","声明式、版本控制的系统配置。随时回滚任何更改。","Декларативная, версионированная конфигурация системы. Откат любого изменения в любое время."], p); }
export function feature_encryption_title(p?: Record<string, string | number>): string { return _t(["Clientseitige Verschlüsselung","Client-Side Encryption","客户端加密","Шифрование на стороне клиента"], p); }
export function feature_encryption_desc(p?: Record<string, string | number>): string { return _t(["Alle Daten werden verschlüsselt, bevor sie Ihr Gerät verlassen. Der Server sieht niemals Ihren Klartext.","All storage is encrypted before it leaves your device. The server never sees your plaintext.","所有存储在离开您的设备之前都经过加密。服务器永远看不到您的明文。","Все данные шифруются до того, как покидают ваше устройство. Сервер никогда не видит открытый текст."], p); }
export function feature_instant_title(p?: Record<string, string | number>): string { return _t(["Sofortstart","Instant Start","即时启动","Мгновенный старт"], p); }
export function feature_instant_desc(p?: Record<string, string | number>): string { return _t(["Kein POST. Keine Treiber. Keine Ladezeiten. Öffnen Sie einen Tab - Ihr OS ist da, genau wie Sie es verlassen haben.","No POST. No drivers. No loading. Open a tab and your OS is there, exactly as you left it.","无 POST。无驱动程序。无加载。打开标签页，您的操作系统就在那里，与您离开时完全相同。","Никаких POST-запросов. Никаких драйверов. Никакой загрузки. Откройте вкладку - и ваша ОС уже там, точно так, как вы её оставили."], p); }
export function feature_bgapp_title(p?: Record<string, string | number>): string { return _t(["Hintergrund-App","Background App","后台应用","Фоновое приложение"], p); }
export function feature_bgapp_desc(p?: Record<string, string | number>): string { return _t(["Optionaler nativer Begleiter für Dateisynchronisation, Peripheriezugriff und Push-Benachrichtigungen von Ihrem Gerät.","Optional native companion for file sync, peripheral access, and push notifications from your device.","可选的本地伴侣应用，用于文件同步、外设访问和来自设备的推送通知。","Опциональный нативный компаньон для синхронизации файлов, доступа к периферии и push-уведомлений с вашего устройства."], p); }
export function feature_collab_title(p?: Record<string, string | number>): string { return _t(["Echtzeit-Zusammenarbeit","Real-Time Collaboration","实时协作","Совместная работа в реальном времени"], p); }
export function feature_collab_desc(p?: Record<string, string | number>): string { return _t(["Gemeinsame Sitzungen auf Dateien und Apps, auf OS-Ebene eingebaut. Nicht nachträglich pro App hinzugefügt.","Shared sessions on files and apps, built at the OS level. Not bolted on per-app.","在操作系统层面构建的文件和应用程序共享会话，而非每个应用程序单独附加的功能。","Совместные сессии на файлах и приложениях, встроенные на уровне ОС. Не надстройка поверх каждого приложения."], p); }
export function bg_app_label(p?: Record<string, string | number>): string { return _t(["Hintergrund-App","Background App","后台应用","Фоновое приложение"], p); }
export function bg_app_title(p?: Record<string, string | number>): string { return _t(["Erweitert sich auf Ihr Gerät.","Extends into your device.","延伸到您的设备。","Расширяется на ваше устройство."], p); }
export function bg_app_desc(p?: Record<string, string | number>): string { return _t(["Installieren Sie die optionale Hintergrund-App, um RizinOS mit Ihrem Gerät zu verbinden. Dateisynchronisation, Peripheriezugriff und native Benachrichtigungen, ohne die Browser-First-Architektur aufzugeben.","Install the optional Background App to bridge RizinOS with your device. File sync, peripheral access, and native notifications, without giving up the browser-first architecture.","安装可选的后台应用，将 RizinOS 与您的设备连接起来。文件同步、外设访问和本地通知，同时保持浏览器优先架构。","Установите опциональное фоновое приложение для связи RizinOS с вашим устройством. Синхронизация файлов, доступ к периферии и нативные уведомления - без отказа от браузерной архитектуры."], p); }
export function sync_bidirectional(p?: Record<string, string | number>): string { return _t(["Bidirektionale Dateisynchronisation zwischen Gerät und Cloud-VFS","Bidirectional file sync between device and cloud VFS","设备与云端 VFS 之间的双向文件同步","Двунаправленная синхронизация файлов между устройством и облачным VFS"], p); }
export function sync_native_dnd(p?: Record<string, string | number>): string { return _t(["Native Drag-and-Drop-Uploads von Ihrem Desktop","Native drag-and-drop uploads from your desktop","从桌面原生拖放上传","Нативная загрузка перетаскиванием с рабочего стола"], p); }
export function sync_backups(p?: Record<string, string | number>): string { return _t(["Kontinuierliche versionierte Backups mit konfigurierbarer Aufbewahrungsdauer","Continuous versioned backups with configurable retention","具有可配置保留期的持续版本化备份","Непрерывные версионированные резервные копии с настраиваемым сроком хранения"], p); }
export function sync_push_notif(p?: Record<string, string | number>): string { return _t(["Push-Benachrichtigungen auch wenn der Browser-Tab geschlossen ist","Push notifications even when the browser tab is closed","即使关闭浏览器标签页也能收到推送通知","Push-уведомления даже при закрытой вкладке браузера"], p); }
export function sync_peripherals(p?: Record<string, string | number>): string { return _t(["Peripherie-Brücke: Kameras, Mikrofone, USB, Seriell","Peripheral bridging: cameras, microphones, USB, serial","外设桥接：摄像头、麦克风、USB、串行","Связь с периферией: камеры, микрофоны, USB, последовательный порт"], p); }
export function sync_offline(p?: Record<string, string | number>): string { return _t(["Offline-Modus mit automatischer Synchronisation bei Wiederverbindung","Offline mode with automatic sync on reconnect","离线模式，重新连接时自动同步","Офлайн-режим с автоматической синхронизацией при восстановлении соединения"], p); }
export function download_for(p?: Record<string, string | number>): string { return _t(["Herunterladen für {platform}","Download for {platform}","下载 {platform} 版本","Скачать для {platform}"], p); }
export function arch_label(p?: Record<string, string | number>): string { return _t(["Architektur","Architecture","架构","Архитектура"], p); }
export function arch_title(p?: Record<string, string | number>): string { return _t(["Saubere Schichten, keine Abkürzungen.","Clean layers, no shortcuts.","清晰的层次，没有捷径。","Чистые слои, никаких компромиссов."], p); }
export function arch_desc(p?: Record<string, string | number>): string { return _t(["Rust-Module werden zu WASM kompiliert und als Kernel-Schicht ausgeführt. SvelteKit steuert die System-Shell. Jede App ist ein isolierter WASM-Prozess mit eigenem Speicherbereich und typisiertem IPC zum OS. Nichts wird implizit geteilt.","Rust modules compile to WASM and run as the kernel layer. SvelteKit drives the system shell. Each app is an isolated WASM process with its own memory space and typed IPC to the OS. Nothing is shared implicitly.","Rust 模块编译为 WASM 并作为内核层运行。SvelteKit 驱动系统外壳。每个应用程序都是一个独立的 WASM 进程，具有自己的内存空间和到操作系统的类型化 IPC。没有任何内容是隐式共享的。","Модули Rust компилируются в WASM и выполняются как уровень ядра. SvelteKit управляет системной оболочкой. Каждое приложение — изолированный WASM-процесс с собственным пространством памяти и типизированным IPC к ОС. Ничего не передаётся неявно."], p); }
export function arch_ipc_note(p?: Record<string, string | number>): string { return _t(["Alle Schichten kommunizieren über typisierte IPC-Schnittstellen","All layers communicate through typed IPC interfaces","所有层通过类型化 IPC 接口进行通信","Все слои общаются через типизированные интерфейсы IPC"], p); }
export function applications_label(p?: Record<string, string | number>): string { return _t(["Anwendungen","Applications","应用程序","Приложения"], p); }
export function apps_title(p?: Record<string, string | number>): string { return _t(["Eine vollständige Suite. Eingebaut.","A full suite. Built in.","完整套件，内置集成。","Полный набор. Встроенный."], p); }
export function apps_desc(p?: Record<string, string | number>): string { return _t(["Jede App teilt ein einheitliches Berechtigungsmodell, Dateiprotokoll und Design-System. Sie sind OS-Bürger, keine Plugins.","Every app shares a unified permission model, file protocol, and design system. They are OS citizens, not plugins.","每个应用程序共享统一的权限模型、文件协议和设计系统。它们是操作系统的一等公民，而非插件。","Каждое приложение использует единую модель разрешений, файловый протокол и дизайн-систему. Они — граждане ОС, а не плагины."], p); }
export function apps_roadmap(p?: Record<string, string | number>): string { return _t(["+ Minecraft-Integration, KI-Assistent, Stripe-Zahlungen, Videoanrufe in der Roadmap","+ Minecraft integration, AI assistant, Stripe payments, video calling in the roadmap","+ Minecraft 集成、AI 助手、Stripe 支付、视频通话已在路线图中","+ Интеграция с Minecraft, ИИ-ассистент, платежи Stripe, видеозвонки в roadmap"], p); }
export function cta_title(p?: Record<string, string | number>): string { return _t(["Ihr OS wartet. Öffnen Sie einen Tab.","Your OS is waiting. Open a tab.","您的操作系统在等待。打开一个标签页。","Ваша ОС ждёт. Откройте вкладку."], p); }
export function cta_desc(p?: Record<string, string | number>): string { return _t(["Keine Downloads. Kein Setup. Funktioniert auf jedem Gerät, jeder Bildschirmgröße, jedem Browser.","No downloads. No setup. Works on any device, any screen size, any browser.","无需下载。无需设置。适用于任何设备、任何屏幕尺寸、任何浏览器。","Без загрузок. Без настройки. Работает на любом устройстве, любом размере экрана, в любом браузере."], p); }
export function cta_button(p?: Record<string, string | number>): string { return _t(["Konto erstellen","Create your account","创建您的账户","Создать аккаунт"], p); }
export function cta_note(p?: Record<string, string | number>): string { return _t(["Dauerhaft kostenlos - Keine Kreditkarte - 10 GB Cloud-Speicher inklusive","Free tier forever - No credit card - 10 GB cloud storage included","永久免费 - 无需信用卡 - 包含 10 GB 云存储","Бесплатно навсегда - Без кредитной карты - 10 ГБ облачного хранилища включено"], p); }
export function login_welcome_label(p?: Record<string, string | number>): string { return _t(["Willkommen zurück","Welcome back","欢迎回来","С возвращением"], p); }
export function login_tagline(p?: Record<string, string | number>): string { return _t(["Ihr OS wartet auf Sie.","Your OS is waiting for you.","您的操作系统在等待您。","Ваша ОС ждёт вас."], p); }
export function login_tagline_desc(p?: Record<string, string | number>): string { return _t(["Melden Sie sich an, um von jedem Gerät, überall auf Ihren Cloud-Desktop zuzugreifen.","Sign in to access your cloud desktop from any device, anywhere.","登录以从任何设备、任何地方访问您的云桌面。","Войдите, чтобы получить доступ к облачному рабочему столу с любого устройства, где угодно."], p); }
export function login_highlight_encrypted(p?: Record<string, string | number>): string { return _t(["Ende-zu-Ende-verschlüsselter Speicher","End-to-end encrypted storage","端到端加密存储","Хранилище со сквозным шифрованием"], p); }
export function login_highlight_any_device(p?: Record<string, string | number>): string { return _t(["Zugriff von jedem Gerät, in jedem Browser","Access from any device, any browser","从任何设备、任何浏览器访问","Доступ с любого устройства, в любом браузере"], p); }
export function login_highlight_instant(p?: Record<string, string | number>): string { return _t(["Sofort - kein Setup, keine Downloads","Instant - no setup, no downloads","即时 - 无需设置，无需下载","Мгновенно - никакой настройки, никаких загрузок"], p); }
export function login_sign_in_title(p?: Record<string, string | number>): string { return _t(["Anmelden","Sign in","登录","Войти"], p); }
export function login_sign_in_desc(p?: Record<string, string | number>): string { return _t(["Geben Sie Ihre Anmeldedaten ein, um fortzufahren.","Enter your credentials to continue.","输入您的凭据以继续。","Введите ваши учётные данные для продолжения."], p); }
export function login_email_label(p?: Record<string, string | number>): string { return _t(["E-Mail","Email","电子邮件","Электронная почта"], p); }
export function login_password_label(p?: Record<string, string | number>): string { return _t(["Passwort","Password","密码","Пароль"], p); }
export function login_forgot_password(p?: Record<string, string | number>): string { return _t(["Passwort vergessen?","Forgot password?","忘记密码？","Забыли пароль?"], p); }
export function login_sign_in_button(p?: Record<string, string | number>): string { return _t(["Anmelden","Sign in","登录","Войти"], p); }
export function login_no_account(p?: Record<string, string | number>): string { return _t(["Noch kein Konto?","Don't have an account?","没有账户？","Нет аккаунта?"], p); }
export function login_create_one(p?: Record<string, string | number>): string { return _t(["Eines erstellen","Create one","创建一个","Создать"], p); }
export function title(p?: Record<string, string | number>): string { return _t(["RizinOS - Das erste Online-Betriebssystem","RizinOS - The First Online Operating System","RizinOS - 第一个在线操作系统","RizinOS - Первая онлайн-операционная система"], p); }
export function description(p?: Record<string, string | number>): string { return _t(["Das moderne webbasierte Betriebssystem, das Ihre Arbeit revolutioniert. Überall verfügbar, immer synchronisiert.","The modern web-based operating system that revolutionizes your work. Available everywhere, always synchronized.","现代的基于网络的操作系统，彻底改变您的工作方式。随时随地可用，始终保持同步。","Современная веб-операционная система, которая революционизирует вашу работу. Доступна везде, всегда синхронизирована."], p); }
export function copyright(p?: Record<string, string | number>): string { return _t(["Alle Rechte vorbehalten.","All rights reserved.","版权所有。","Все права защищены."], p); }
export function features(p?: Record<string, string | number>): string { return _t(["Funktionen","Features","功能","Функции"], p); }
export function overview(p?: Record<string, string | number>): string { return _t(["Überblick","Overview","概览","Обзор"], p); }
export function performance(p?: Record<string, string | number>): string { return _t(["Leistung","Performance","性能","Производительность"], p); }
export function security(p?: Record<string, string | number>): string { return _t(["Sicherheit","Security","安全性","Безопасность"], p); }
export function integration(p?: Record<string, string | number>): string { return _t(["Integration","Integration","集成","Интеграция"], p); }
export function documentation(p?: Record<string, string | number>): string { return _t(["Dokumentation","Documentation","文档","Документация"], p); }
export function getting_started(p?: Record<string, string | number>): string { return _t(["Erste Schritte","Getting Started","快速开始","Начало работы"], p); }
export function api_reference(p?: Record<string, string | number>): string { return _t(["API-Referenz","API Reference","API 参考","API справочник"], p); }
export function tutorials(p?: Record<string, string | number>): string { return _t(["Tutorials","Tutorials","教程","Руководства"], p); }
export function pricing(p?: Record<string, string | number>): string { return _t(["Preise","Pricing","价格","Цены"], p); }
export function enterprise(p?: Record<string, string | number>): string { return _t(["Enterprise","Enterprise","企业版","Корпоративным клиентам"], p); }
export function privacy_policy(p?: Record<string, string | number>): string { return _t(["Datenschutz","Privacy Policy","隐私政策","Политика конфиденциальности"], p); }
export function terms_of_service(p?: Record<string, string | number>): string { return _t(["AGB","Terms of Service","服务条款","Условия использования"], p); }
export function cookies(p?: Record<string, string | number>): string { return _t(["Cookies","Cookies","Cookies","Cookies"], p); }
export function imprint(p?: Record<string, string | number>): string { return _t(["Impressum","Imprint","法律信息","Юридическая информация"], p); }
export function product(p?: Record<string, string | number>): string { return _t(["Produkt","Product","产品","Продукт"], p); }
export function resources(p?: Record<string, string | number>): string { return _t(["Ressourcen","Resources","资源","Ресурсы"], p); }
export function status(p?: Record<string, string | number>): string { return _t(["Status","Status","状态","Статус"], p); }
export function blog(p?: Record<string, string | number>): string { return _t(["Blog","Blog","博客","Блог"], p); }
export function company(p?: Record<string, string | number>): string { return _t(["Unternehmen","Company","公司","Компания"], p); }
export function about_us(p?: Record<string, string | number>): string { return _t(["Über uns","About Us","关于我们","О нас"], p); }
export function careers(p?: Record<string, string | number>): string { return _t(["Karriere","Careers","招聘","Карьера"], p); }
export function contact(p?: Record<string, string | number>): string { return _t(["Kontakt","Contact","联系方式","Контакты"], p); }
export function legal(p?: Record<string, string | number>): string { return _t(["Rechtliches","Legal","法律信息","Правовая информация"], p); }
export function open_your_os(p?: Record<string, string | number>): string { return _t(["Ihr OS öffnen","Open your OS","打开您的操作系统","Открыть вашу ОС"], p); }
export function log_in(p?: Record<string, string | number>): string { return _t(["Anmelden","Log in","登录","Войти"], p); }
export function language(p?: Record<string, string | number>): string { return _t(["Sprache","Language","语言","Язык"], p); }